FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt -q

RUN apt-get -qq update && \
    apt-get -qq install wget && \
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt -qq install -y ./google-chrome-stable_current_amd64.deb && \
    rm google-chrome-stable_current_amd64.deb

COPY src .

ENTRYPOINT ["python3", "main.py"]