version: "3.8"

services:
  db:
    image: postgres
    container_name: WTTJ-database
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
